"use strict";
/* Concepts curriculum for the explainer. Data-only; rendered by app.js.
   Coverage contract: every concept the research touches, ordered from mesh
   foundations down to the BLE radio and direction-finding floor. Each item:
   term, which-layer, short answer, evidence tag, and the site section that
   expands it. Text is a faithful digest of research/paper/01_manuscript.md,
   research/paper/ip/00_ip_analysis.md, and DOCUMENTATION.md. Tag meanings
   follow the paper's evidence bands (Sec 35.1): CAN=confirmed fact, IMP=
   implemented in repo, RES=measured in sim/reference, PRO=proposed, FAIL=
   reported failure (RETURN), NOT-RUN=planned experiment not executed. */

window.CONCEPTS = [
  {
    chapter: "1 · Foundations — why this is hard, and the whole-stack answer",
    lead: "The project is infrastructure-independent crowd navigation for indoor/disaster scenes. Every phone is a node; no tower, GPS, beacons, or cloud. This chapter is the why.",
    items: [
      { term: "Infrastructure independence", tag: "CAN", cls: "measured",
        ans: "The system must work when cellular is jammed and GPS is blocked, so it cannot depend on any pre-existing radio or coordinate service. It uses only the radios a commodity phone already has." },
      { term: "Why beacons and cloud anchors fail", tag: "CAN", cls: "measured",
        ans: "Installing fixed beacons (AoD arrays, UWB anchors, fingerprint maps) pre-supposes a maintained, powered fixed installation at the exact scene that is unplanned; that is the situation emergency response is worst at." },
      { term: "The whole stack, not a component", tag: "IMP", cls: "measured",
        ans: "A person's question — \u201cwhich way do I walk?\u201d — is last in a chain: identity, radio plumbing, packet, topology, gradient, geometry, then guidance. The paper's contribution is the integration of all eleven layers with honesty rules." },
      { term: "\u201cWhat, not just who\u201d", tag: "PRO", cls: "open",
        ans: "Classic DTN answers who can reach whom; Find Us additionally answers where they are relative to you and whether that where is true. The consistency engine is the part that keeps the navigable gradient honest." },
      { term: "Eleven layers of architecture", tag: "IMP", cls: "measured",
        ans: "Radio plausibility, link/discovery, packet/coding, hop/relay, routing graph, gradient, spatial graph (VRLG), consistency, navigation rendering, terminal UI, and platform compliance — bottom-up. No single layer is new; the coupling is." },
      { term: "Evidence bands (CAN/PRO/IMP/EXP/RES/FAIL)", tag: "CAN", cls: "measured",
        ans: "Every claim carries a band: CAN = cited fact, PRO = proposed mechanism, IMP = implemented in the repo, EXP = experiment, RES = measured result, FAIL = openly reported failure. NOT-RUN markers mark gaps explicitly. Nothing is silently mixed." },
    ],
  },

  {
    chapter: "2 · The BLE radio floor — what bytes can physically ride",
    lead: "Before any protocol there is the radio. BLE's advertising files are the whole transport, and their ceilings force the packet design.",
    items: [
      { term: "BLE advertising channels 37–39", tag: "CAN", cls: "measured",
        ans: "BLE has 40 RF channels; exactly 3 (37–39) are dedicated advertising channels, the rest are data channels. Advertising packets ride the 3; discovery is itself a scheduling problem across channel and time." },
      { term: "The byte ceilings", tag: "CAN", cls: "measured",
        ans: "Legacy advertising payload = 31 B total; type 0xFF manufacturer block = 27 B usable; a custom AD record can reach 29 B; iOS background serializes/coalesces to ≤ 23 B (dual-AD) with overflow items delayed. The packet is designed to fit the tightest: 23 B." },
      { term: "Scan/advertise half-duplex trade", tag: "CAN", cls: "measured",
        ans: "A device alternates between advertiser and scanner. Two phones meet as a trade — A's advertisement must overlap B's scan window. Discovery is stochastic, not scheduled; the protocol uses a willing-to-advertise discipline." },
      { term: "Energy asymmetry", tag: "RES", cls: "measured",
        ans: "Transmitting an advert slot is cheap (~1.32 µAh/s in the constant model); listening on the advertising channel is ~10× (≈14.23 µAh/s at 10 Hz scan). Co-design: spend broadcast slots, hoard listen time." },
      { term: "Body shadowing (~50 dB)", tag: "CAN", cls: "measured",
        ans: "A human body can occlude ~50 dB. That breaks the RSSI→distance monotonic assumption — a fundamental limit, which is why geometry relies on witnesses, not on one RSSI sample." },
      { term: "Connection-free topology", tag: "IMP", cls: "measured",
        ans: "Edges are formed by hearing advertisements, never by opening GATT connections. This dodges the OS ~8-concurrent-connection ceiling: node degree is bounded by duty cycle and energy, not by the connection cache. The adversarial critique (Sec 39.2) is answered exactly here." },
      { term: "Byte-budget audit", tag: "RES", cls: "measured",
        ans: "56 bits of core payload + Hamming(7,4) ECC = 13 B total — fits the 27 B Type-0xFF ceiling and the 23 B iOS dual-AD ceiling with headroom; extensions are chunked." },
    ],
  },

  {
    chapter: "3 · Packet & coding — the 13-byte frame",
    lead: "The whole protocol lives in 56 bits + error correction. This chapter is that envelope.",
    items: [
      { term: "The 56-bit envelope", tag: "IMP", cls: "measured",
        ans: "version(2) · type(4) · seq(8) · src-id(8) · dst-hint(3) · hop-budget(5) · payload(26) = 56 bits = 7 B; ECC doubles it to 13 bytes under every ceiling." },
      { term: "Hamming(7,4) FEC", tag: "IMP", cls: "measured",
        ans: "Nibble-level error correction on the 13-byte frame. Verified: 2,240 boundary cases + 100,000 random round-trips pass; 14-bit-flip FEC recovers; canonical vector 17a53ee2998f42." },
      { term: "Envelope MAC (16-bit)", tag: "IMP", cls: "measured",
        ans: "A rolling authenticator over (SOS_ID ‖ EPOCH ‖ PKT_TYPE), keyed by the incident team key, sits inside the payload. It defeats casual spoofing and replay sniffing; collision odds ~2⁻¹⁶ per attempt — an honest guard, not full crypto." },
      { term: "Transaction taxonomy", tag: "IMP", cls: "measured",
        ans: "Six classes: hello/presence, rpt (relationship report), sos (gradient beacon), ack (receipt), cmd (mode/rate), chunk (reassembled application data). Each maps to a packet type, cadence, and priority." },
      { term: "v2/v3 codec compatibility", tag: "IMP", cls: "measured",
        ans: "The version field selects the codec; v3 extends payload interpretation, never the frame contract — a versioned fleet (mixed apps/OS versions) parses both." },
      { term: "Relay/forward/suppress/cache gate", tag: "IMP", cls: "measured",
        ans: "Every arrival passes one of four decisions — relay (new, budget>0, meter open), forward (targeted), suppress (deduped/meter closed/absorbed), cache (budget exhausted, mule slot). This is core/protocol.py dispatch." },
      { term: "Timers & stale-edge TTL", tag: "RES", cls: "measured",
        ans: "Trickle interval I_min→I_max with redundancy K (RFC-6206 style) trading churn vs silence; stale edges decay on a re-aging schedule so a ghost never outlives its truth by more than one horizon." },
    ],
  },

  {
    chapter: "4 · Topology & the SOS gradient — the mesh core",
    lead: "How a crowd turns heard-radios into a navigable hop field, safely.",
    items: [
      { term: "The SOS gradient", tag: "IMP", cls: "measured",
        ans: "An SOS labels every relaying node with distance-to-source: hop count, e2e latency, residual budget, and gradient direction. Gradient direction is derived from the spatial graph — SOS is a navigable signal, not just a beacon." },
      { term: "Hop adoption", tag: "IMP", cls: "measured",
        ans: "A node adopts hop H when it hears a live claim of H−1; it holds only numbers it personally adopted. TTL 8 caps the radius; the gradient does not try to own the world." },
      { term: "Freshness & expiry", tag: "IMP", cls: "measured",
        ans: "Reference build: nodes expire at 120 s, edges at 60 s of silence, route claims live 120 s. Expiry tracks physical reach, not a buddy list." },
      { term: "One-hop backing / the ghost rule", tag: "IMP", cls: "measured",
        ans: "A device advertises hop H only while it still re-hears a live H−1 claim. Lose the backer and you fall silent — gradients collapse one ring at a time from the origin. This structurally forbids fabricated routes (watch it in the Gradient sim)." },
      { term: "Ghost-heal & mule overwrite", tag: "IMP", cls: "measured",
        ans: "A ghost advertises its last-known gradient with rising uncertainty, or lets a fresher relay overwrite it (mule slots). Honest subtraction beats invented directions." },
      { term: "Trickle broadcast discipline", tag: "RES", cls: "measured",
        ans: "Jittered, duty-cycled advertising: small frames, frequently, predictably but not colliding — steady-state receiver load is O(k) frames/s, not O(N). Async coverage restored from 1.51% → 99.86% under iOS coalescing (run exp_009_async_trickle)." },
      { term: "Local-report absorption / anti-storm", tag: "RES", cls: "measured",
        ans: "A node absorbs its neighbors' re-listened reports locally and re-broadcasts only its delta; the trickle meter closes for repeated content. SOS bypasses absorption — the one accepted storm vector, for emergency latency." },
      { term: "Quantized spatial congruence", tag: "PRO", cls: "open",
        ans: "Trickle resets I_min on inconsistency; raw spatial state is never \u201cconsistent\u201d, so congruence is defined on a quantized snapshot anchor, with at-threshold drift re-using I_max. The corrective the adversarial critique demanded (E31)." },
      { term: "SOS state machine", tag: "IMP", cls: "measured",
        ans: "IDLE → ARMING → ARMED → FIRING → PROPAGATING → CLEAR (→ IDLE). Arm/fire separation lets a non-typing victim arm by press; a motion sentinel fires only where sensor evidence says \u201cI am down\u201d; CLEAR kills ghost gradients." },
      { term: "Dynamic topology & churn", tag: "IMP", cls: "measured",
        ans: "Topology is a flow: arrival (probe → OBSERVED → attach), departure (age-out, no ghost unless SOS), re-appearance (re-register if envelope-consistent). Churn lowers I_min; stationary silence raises I_max." },
      { term: "Partitions & the merge protocol", tag: "IMP", cls: "measured",
        ans: "The system must begin partitioned and converge later. Merge: bridge discovery → frame tie-break (the more witnessed frame survives) → relative-coordinate recompute → re-absorption with meter opened, then closed." },
      { term: "Reconnection failure signature", tag: "IMP", cls: "measured",
        ans: "If reconciliation fails, the engine holds both frames as separate OBSERVED tiers, marks \u201cframe ambiguity\u201d and retries with backoff. Honest ambiguity is preferred over false consensus." },
    ],
  },

  {
    chapter: "5 · Sensing & relative localization",
    lead: "What a commodity phone can honestly measure, and the traps in turning that into \u201cwhere\u201d.",
    items: [
      { term: "Sensor classes", tag: "CAN", cls: "measured",
        ans: "RF ranging (RSSI→distance, crude), IMU (PDR: steps+heading, drifts), barometer (resolution yes, absolute offset noisy — good for change/floor-gating), magnetometer (compass, distorted indoors), optional UWB/arrays only as accelerators, plus crowd side-channels." },
      { term: "Sensing honesty contract", tag: "IMP", cls: "measured",
        ans: "Every edge carries (distance, direction, accuracy) where accuracy derives from the weakest sensor in the chain. Uncertainty tiers are stored; a drifty compass never masquerades as survey-grade." },
      { term: "The frame problem (FAIL)", tag: "FAIL", cls: "measured",
        ans: "The central trap: phones report sensor-local headings, and propagating vectors in the local frame shears the whole structure. The first implementation corrupted gradients exactly this way; world-relative propagation fixed it — openly reported as a FAIL." },
      { term: "Hop-length error vs density", tag: "RES", cls: "measured",
        ans: "Relative-position error grows with hop-chain length, but more slowly at higher density (more witnesses bound direction). Simulated at 2,000 nodes, 50 MC, 200×200 m." },
      { term: "Directional-coverage loss", tag: "RES", cls: "measured",
        ans: "Body shadowing leaves some edges with no direction at all. Missing-direction edges are 1-DoF placeholders with wide uncertainty: routing still uses them, navigation marks them \u201cdirection unknown\u201d." },
      { term: "Uncertainty tiers", tag: "IMP", cls: "measured",
        ans: "EXACT (cross-checked, navigation-grade) · OBSERVED (one-shot, routing-grade) · DERIVED (chain-computed, route-hint) · GHOSTED (stale, candidate) · Unknown. No tier upgrade without a witness — the anti-rumor axiom." },
      { term: "Landmark conflation (FAIL)", tag: "FAIL", cls: "measured",
        ans: "The first Kalman landmark tracker conflated neighbours at ~3.5 m spacing when 3-sigma ≈ 3.3 m: the arrow snapped between them. Fixed with multi-hypothesis gating plus graph-cycle consistency on associations — reported so others don't relive it." },
      { term: "VRLG — virtual relative landmark graph", tag: "IMP", cls: "measured",
        ans: "A labelled graph whose vertices are devices plus virtual landmarks, coordinates relative to a trusted landmark frame. Derivative of DV-hop/APS & AFL lineage, but with an explicit shared frame. It is the canonical \u201cwhere\u201d answer-buffer." },
      { term: "Report discipline (rpt)", tag: "IMP", cls: "measured",
        ans: "Neighborhood reports are on-change chirps gated by the trickle meter — the information-injection channel for every layer above discovery. Propagated: deltas, landmark frames, gradient labels, freshness. Not propagated: raw RSSI, IMU logs, absolute coords." },
    ],
  },

  {
    chapter: "6 · Consistency & geometry — the anti-rumor authority",
    lead: "A gossip graph that is 80% true and 20% rumor navigates worse than one that is honestly incomplete. This is the machinery that keeps topology truthful.",
    items: [
      { term: "The consistency engine", tag: "IMP", cls: "measured",
        ans: "Local, cheap cross-checks that are first-class citizens: cross-edge agreement, signed-direction cycle closure, merge-time recompute, and aging. Cost is O(neighbour set) per event — phone-scale." },
      { term: "Cheating-edge rejection", tag: "PRO", cls: "open",
        ans: "An adversarial node injecting impossible edges fails closed-cycle geometry quickly — local cost, no cloud. Unit-tested; live-radio exploit testing is E-series open (NOT-RUN)." },
      { term: "Kabsch/SVD reflection rule", tag: "PRO", cls: "open",
        ans: "A naive SVD registration can return a mirror image (det R = −1) when point sets are near-coplanar. The engine checks det(R) ≈ +1, sign-flips the final V column on −1 (standard Kabsch correction), and rejects any frame whose residual stays negative. E32 verifies (NOT-RUN)." },
      { term: "Robust PGO / false loop closures", tag: "PRO", cls: "open",
        ans: "Where pose-graph optimization is used, it uses robust loss (Huber/Cauchy) or switchable constraints so one false RSSI loop closure cannot warp a trajectory, plus incremental (iSAM2-style) solves for mobile CPU. Full-scale PGO-with-switchables is a future E item." },
      { term: "Reference-frame resolution", tag: "IMP", cls: "measured",
        ans: "All coordinates live in a shared world-relative frame chosen at VRLG initialisation; device frames are detected and their rotation measured, never assumed. The FAIL report documents why this matters." },
      { term: "Coupling: SOS + spatial graph", tag: "RES", cls: "measured",
        ans: "Gradient labels and spatial labels ride the same lane, so a relay must hold both gradient and spatial context before forwarding a navigable SOS, and the consistency engine applies one honesty rule to both. Flooding alone says an SOS exists; coupling says where it is." },
      { term: "The anti-rumor lemma", tag: "PRO", cls: "open",
        ans: "Where edges carry cycle-checkable signed directions, a gradient cannot loop back to its source: the closed-walk check closes to ∅ and the ghost rule suppresses the re-send. Scoped honestly: on direction-poor/tree subgraphs no cycle check exists and only ghost demotion guards. Provisional on E31/E32." },
    ],
  },

  {
    chapter: "7 · Guidance — from graph to \u201cwalk that way\u201d",
    lead: "The human-facing layer: how a hop + geometry turns into a truthful arrow, and what the terminal shows.",
    items: [
      { term: "The conditional direction lemma", tag: "PRO", cls: "open",
        ans: "If a path of live H−1 claims exists to you, your next hop is on a path to the origin — under the freshness condition and honest neighbour claims. The caveats are explicit; verification is E31/E32, marked NOT-RUN." },
      { term: "Path discovery on the VRLG", tag: "IMP", cls: "measured",
        ans: "Shortest-path cost = hop-weighted duration + uncertainty penalty, where penalty uses edge tier. The router therefore avoids ghosted and single-hearsay edges; the result is a hop-path plus a spatial trace." },
      { term: "Rendering modes", tag: "IMP", cls: "measured",
        ans: "Composite arrow (steepest descent, glanceable), edge-of-screen reverse-chevron icons (poor-man's AR), a purely-relative path polyline, and an orbital track (\u201c40 m at heading 115°, ~55 steps\u201d). \u201cDirection unknown\u201d is always explicit — never an invented arrow." },
      { term: "Z-axis & floor transitions", tag: "PRO", cls: "open",
        ans: "Barometer evidence gates floor-change events, not absolute floors. Routing works over VRLG floor-edges; navigation says \u201cchange level\u201d, never \u201cgo to floor 3\u201d, because absolute floor identity is unavailable." },
      { term: "Terminal-beacon early binding", tag: "RES", cls: "measured",
        ans: "The terminal (last anchor, the victim's device) starts advertising SOS presence immediately, before the graph converges — simulated order-of-magnitude ETA gains for responder localisation." },
      { term: "Fallback ladders", tag: "IMP", cls: "measured",
        ans: "Communication: BLE-native → BLE-state/lease escalation → WiFi-direct → USB/Ethernet chains → foot mule. Localization: VRLG geometric → topological → hop-count → terminal beacon → nomadic relay. Every step is a declared mode, not a surprise." },
      { term: "Failure response loop", tag: "IMP", cls: "measured",
        ans: "DETECT → CLASSIFY (transient/structural) → RESPOND → FALLBACK → RECOVER, applied uniformly across communication, localization, navigation. Failure modes FM1–FM12 each enumerate this loop." },
    ],
  },

  {
    chapter: "8 · Navigation tiers — the strength ladder, weakest to strongest",
    lead: "A phone picks the strongest tier it can honestly measure on the current link. The end of this ladder is direction — the \u201cBLE direction\u201d question, answered honestly.",
    items: [
      { term: "Tier 1 · Hop gradient", tag: "IMP", cls: "measured",
        ans: "Every phone has it: adopt, advertise while backed, walk toward the freshest lower-hop neighbour. Purely topological; a compass-free, maths-free ground floor." },
      { term: "Tier 2 · RSSI near/far band", tag: "IMP", cls: "measured",
        ans: "Threshold on dBm → NEAR/FAR. Even a BLE4 phone can do it; steers around corners without a range number. Risk: a metal wall reads as distance when it is attenuation." },
      { term: "Tier 3 · RSSI log-distance", tag: "PRO", cls: "open",
        ans: "d = d0·10^((P0−R)/10n). Open-air physics of log-decay; walls and crowds twist n. Coefficients are a field-open question (E15), NOT-RUN — the site says so wherever it appears." },
      { term: "Tier 4 · Compass heading", tag: "IMP", cls: "measured",
        ans: "Peer reports a CL-relative bearing; your magnetometer turns it into \u201cwalk 023° until the hop drops\u201d. Indoors, rebar bends the compass — a hint, never the whole map." },
      { term: "Tier 5 · IMU motion vector", tag: "IMP", cls: "measured",
        ans: "Step detection + heading integrates your own pace — no radio needed this second, but drift accumulates; only as good as the last trusted fix. AR-gated PDR (run exp_011_ar_gated_pdr) suppresses 100% of pocket/mosh false vectors and cuts drift 9.86×." },
      { term: "Tier 6 · Rotate-to-find (sweep)", tag: "PRO", cls: "open",
        ans: "Sweep 360°, log RSSI vs device bearing, take the peak. On plain phones this is RSSI-class observation, not AoA hardware; bearings are provisional on E17 (NOT-RUN). The manuscript is explicit: honesty over fantasy." },
      { term: "Tier 7 · Elevation / floor (baro)", tag: "PRO", cls: "open",
        ans: "ΔP → Δelevation via the hypsometric relation, binned to floors or FLOOR_UNCERTAINTY. HVAC and weather drafts are real; cross-floor resolution is E21/E22, NOT-RUN." },
      { term: "Why not AoA/AoD on phones", tag: "CAN", cls: "measured",
        ans: "BLE 5.1 angle of arrival needs a switched antenna array and CTE IQ sampling in the locator; commodity phones have none. The adversarial critique (§39.1) is accepted and baked in: the route out of a direction hole is corruptible-but-correctable witnesses, never a phase array." },
      { term: "UWB / channel-sounding as accelerants, not requirements", tag: "CAN", cls: "measured",
        ans: "IEEE 802.15.4z UWB and future BLE channel sounding can upgrade edge quality when present (DirectionCapability negotiation), but are walled/non-universal. Everything navigates on the weakest common tier." },
    ],
  },

  {
    chapter: "9 · Security & privacy — trust without a server",
    lead: "No accounts, no cloud, no PKI. Trust is per-incident, pseudonymous, and honest about what it cannot promise.",
    items: [
      { term: "Team key from a text link", tag: "IMP", cls: "measured",
        ans: "Everyone who scans the same incident link derives the same team key — the whole crowd authenticates each other with zero server sync. The link is the entire secret-distribution channel." },
      { term: "Anti-spoofing", tag: "IMP", cls: "measured",
        ans: "Envelope MAC over (SOS_ID ‖ EPOCH ‖ PKT_TYPE) + sequence replay guard. 16-bit forgery ≈ 0.15–0.18% per message at unit-test level — the audit replays/forges all day and the graph never moves." },
      { term: "Unlinkability", tag: "IMP", cls: "measured",
        ans: "Short-lived src-id aliases rotate on a schedule so a passive observer cannot correlate trajectories across rotations. Linkability is a declared open gap (RQ18), not a solved anonymity claim." },
      { term: "Graph poisoning defense", tag: "IMP", cls: "measured",
        ans: "Closed-cycle checks reject impossible edges; a forged SOS with no witnessed gradient dies at first tier-demotion; identity loss shows as a tier drop." },
      { term: "DTN crypto attacks (TOCTOU / TOFU / traceability)", tag: "PRO", cls: "open",
        ans: "Adopted as explicit threat cases, not solved facts: key-pinning + re-verify at every handoff (TOCTOU), out-of-band QR fingerprint verification for first contact (TOFU without PKI), no single network-wide broadcast key + no unbounded payloads (broadcast/DoS), and alias rotation + IRK hygiene (traceability)." },
      { term: "Client-only privacy stance", tag: "PRO", cls: "open",
        ans: "No server gathers graph data; computation is on-device. An observer can learn presence/density and SOS traffic volume — never positions without participating. Passive-linkability of star nodes remains an honest research gap." },
      { term: "Governance & at-risk communities", tag: "MAY", cls: "open",
        ans: "Ephemeral by design (store TTLs, alias rotation); a victim can refuse to advertise while still listening (tiered disclosure). Civil-society deployments require explicit consent and traceability-impact statements — governance work, not solved protocol." },
    ],
  },

  {
    chapter: "10 · Platforms, energy, scale — the OS-phase reality",
    lead: "Android and iOS carve the discipline. This chapter is where theory meets the operating system.",
    items: [
      { term: "Android admission & foreground service", tag: "IMP", cls: "measured",
        ans: "Android 12+ gates BLE on fine-location; API 34 requires an explicit foreground-service type (CONNECTED_DEVICE / LOCATION) with a persistent notification. The app runs inside the FGS when participating and degrades to receiver-only otherwise — no \u201cinvisible mesh\u201d illusion." },
      { term: "Background survival", tag: "IMP", cls: "measured",
        ans: "Foreground service + state-machine continuity; opportunists sync via scheduled scan windows (WorkManager-style), and process deaths re-seed from envious neighbours. Quantized report discipline matches the platform's execution budget." },
      { term: "Vendor variance", tag: "PRO", cls: "open",
        ans: "OEM kill-layers throttle BLE scanning/advertising in unquantified ways. RQ21 acknowledges the matrix; a device matrix is E21, NOT-RUN." },
      { term: "iOS ceiling & background modes", tag: "RES", cls: "measured",
        ans: "Background advertising coalesces to ≤ 23 B; the 13-byte core fits, extensions chunk into overflow. iOS background BLE is a reserved capability; CoreBluetooth arbiteres cadence. Equal-degree Android/iOS participation is disclaimed honestly (RQ16)." },
      { term: "Energy regime & budgeting", tag: "RES", cls: "measured",
        ans: "Simulated constant-model duty: a 3-hour background shift costs order-units of mA·h; emergency-aware 10× bursts are explicitly budgeted and accounted. No field battery curves — the numbers are protocol-constant-derived, flagged as such." },
      { term: "Scalability envelope", tag: "RES", cls: "measured",
        ans: "Qualitative results at 2,000 nodes / 50 MC / 200×200 m / hops 1–11: density helps topology, landmarks dominate error, absorption suppresses storms, early-binding gates improve terminal ETA. Operational venue scale is expressly unproven." },
      { term: "Theory of scaling", tag: "PRO", cls: "open",
        ans: "VRLG is bandwidth-friendly: small deltas, local stores, O(neighbour set) consistency checks. The 2,000-node envelope is a simulation bound, not a proven operational bound." },
    ],
  },

  {
    chapter: "11 · Evidence, critique, and the honest exit",
    lead: "What was actually measured (with run-ids), what a hostile review said, and where the next researcher's feet are.",
    items: [
      { term: "The experimental program (E1–E23)", tag: "RES", cls: "measured",
        ans: "Executed as unit/simulation: E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E14, E16, E18, E19, E20, E23. NOT-RUN: E13 (baro gating), E15 (fallback signatures), E17 (iOS overflow), E21 (device matrix), E22 (real-field smoke), plus critique-driven E31/E32." },
      { term: "Signature results (run-anchored)", tag: "RES", cls: "measured",
        ans: "E3/exp_002: contention success 0.023→0.901 with k=3 suppression. exp_009: async coverage 1.51%→99.86%, delivery 99.98% under 70% background coalescing. exp_011: AR-gated PDR cuts drift 32.9 m→3.3 m (9.86×), 100% false-vector suppression. exp_012: terminal arrival ≤5 m 79.92%→88.35%." },
      { term: "RQ-by-RQ status", tag: "RES", cls: "measured",
        ans: "Each RQ1–RQ21 is tagged: answered-in-sim with run-id, qualitative, or provisional-on-E31 / NOT-RUN. The reviewer panel flagged exactly two made-up-looking numbers; both are now measured or provisional." },
      { term: "The adversarial critique (Sec 39)", tag: "PRO", cls: "open",
        ans: "An external critique attacked AoA feasibility, invisible-mesh background operation, Trickle in perpetual spatial inconsistency, Kabsch/SVD reflections, robust PGO, and DTN crypto. Valid points are designed-in as repair rules (E31, E32, det(R) rule, OOB/QR, key pinning); the framing that the paradigm is infeasible is rejected." },
      { term: "Limitations", tag: "CAN", cls: "measured",
        ans: "No hardware field runs; simulation lacks true shadowing/overflow/randomization; RSSI is coarse under ~50 dB occlusion; 16-bit MAC is a guard; energy is constant-model; vendor/sensor variance unquantified; HCI claims are design; venue scale unproven." },
      { term: "Novelty / IP markers", tag: "MAY", cls: "open",
        ans: "The companion IP analysis isolates candidate assemblies C1–C8, each with prior art, mechanism, difference, and risk; markers are [MAY, LEGAL-REVIEW-RESERVED]. No patentability position is taken; candidate assemblies are integrations of known components." },
      { term: "Remaining research gaps", tag: "OPEN", cls: "notrun",
        ans: "Field hardware validation (E22/E13/E17/E21), app-store policy run, full crypto under BLE budget, HCI/glanceability measurement, scaling beyond 2,000 nodes with reconnection storms, and live-radio adversarial robustness. The honest exit report names them all." },
    ],
  },
];